#eureka:
#  instance:
#    prefer-ip-address:  true
#  client:
#   fetch-registry: true
#   register-with-eureka:  true
#   service-url:
#      defaultZone: http://localhost:8761/eureka
server:
  port : 8085 
  
spring:
  config:
    import: optional:configserver:http://localhost:8084
     
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
      - id : Employee-Service
        uri: lb://Employee-Service
        predicates:
        - Path=/oilc_suit/employees/**
      - id : Trainer-Service 
        uri: lb://Trainer-Service
        predicates:
        - Path=/oilc_suit/trainer/**
        
      
  